apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: java-demo
spec:
  replicas: 5

  selector:
    matchLabels:
      app: java-app

  template:
    metadata:
      labels:
        app: java-app

    spec:
      containers:
      - name: java-app

        image: ghcr.io/pattabhi45/spring-boot-crud-postgres-adminer:v1.0.5

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: java-config
              key: SPRING_DATASOURCE_URL

        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: java-secret
              key: SPRING_DATASOURCE_USERNAME

        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: java-secret
              key: SPRING_DATASOURCE_PASSWORD