apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: java-demo
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: java-demo
data:
  POSTGRES_DB: productsdb