name: Update Deployment Image

on:
  repository_dispatch:
    types:
      - deploy

permissions:
  contents: write

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Payload
        run: |
          echo "Tag: ${{ github.event.client_payload.tag }}"
          echo "Image: ${{ github.event.client_payload.image }}"

      - name: Update Deployment Manifest
        run: |
          IMAGE="${{ github.event.client_payload.image }}"

          sed -i "s|image: .*|image: ${IMAGE}|g" k8s/java-deployment.yaml

          echo "Updated Manifest:"
          cat k8s/java-deployment.yaml

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add k8s/java-deployment.yaml

          git commit -m "Update image to ${{ github.event.client_payload.image }}" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push origin main