name: CD Pipeline
 
on:
  repository_dispatch:
    types:
      - deploy-app

  workflow_dispatch:
 
permissions:
  contents: write
 
jobs:
  update-manifest:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Update Image Version
        run: |
          sed -i "s|image: .*|image: magibalan07/spring-boot-crud-postgres-adminer:${{ github.event.client_payload.image_tag }}|g" 05-java-deployment.yaml
 
      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
 
          git add 05-java-deployment.yaml
 
          git commit -m "Update image to ${{ github.event.client_payload.image_tag }}" || true
 
          git push
 
